[workspace]
resolver = "3"
members = [
    "bytecode",
    "collectors/dummy_heap",
    "collectors/mark_sweep",
    "heap_api",
    "heap_tests",
    "heap_utils",
    "interpreter",
    "js_compiler",
    "kette_compiler",
    "kette_parser",
    "js_runtime",
    "kette_runtime",
    "trace",
    "vm",
    "vm_core",
]

[workspace.package]
edition = "2024"

