[package]
name = "vm"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "ovm"
path = "src/main.rs"

[dependencies]
heap_api = { path = "../heap_api" }
bytecode = { path = "../bytecode" }
ir = { path = "../ir" }
js_compiler = { path = "../js_compiler" }
mark_sweep = { path = "../collectors/mark_sweep" }

[features]
stress-minor-gc = []
