[package]
name = "kette_runtime"
version = "0.1.0"
edition.workspace = true

[dependencies]
vm_core = { path = "../../vm_core" }

[dev-dependencies]
interpreter_match_loop = { path = "../../interpreter_match_loop" }
kette_compiler = { path = "../kette_compiler" }
mark_sweep = { path = "../../collectors/mark_sweep" }
