[package]
name = "interpreter_become"
version = "0.1.0"
edition = "2024"

[dependencies]
vm_core = { path = "../vm_core" }
bytecode = { path = "../bytecode" }

[dev-dependencies]
js_compiler = { path = "../js_compiler" }
js_runtime = { path = "../js_runtime" }
mark_sweep = { path = "../collectors/mark_sweep" }

interpreter_match_loop = { path = "../interpreter_match_loop" }
