[package]
name = "js_compiler"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytecode = { path = "../bytecode" }
ir = { path = "../ir" }
oxc_allocator = "0.151.0"
oxc_ast = "0.151.0"
oxc_ast_visit = "0.151.0"
oxc_parser = "0.151.0"
oxc_semantic = "0.151.0"
oxc_span = "0.151.0"
oxc_syntax = "0.151.0"
